Repository Fall-2023-SE-Group-14/DollarBot, pull requests merged in 2023-11, with the labels that each got.

#5 Create CITATION.cff
  CITATION.cff
Labels: documentation, citation

#26 fixed Flake issues
  .flake8
  .github/workflows/styleChecker.yml
  code/__init__.py
  code/add.py
  code/add_recurring.py
  code/add_user.py
  code/budget.py
  code/budget_delete.py
  code/budget_update.py
  code/budget_view.py
  code/category.py
  code/code.py
  code/csvfile.py
  code/delete.py
  code/delete_expense.py
  code/delete_user.py
  code/display.py
  code/edit.py
  code/helper.py
  code/history.py
  code/pdf.py
  code/reminder.py
  code/send_mail.py
  setup.py
  test/test_add.py
  test/test_add_recurring.py
  test/test_add_user.py
  test/test_budget.py
  test/test_budget_delete.py
  test/test_budget_update_rest.py
  test/test_budget_update_run.py
  test/test_budget_view.py
  test/test_category.py
  test/test_csvfile.py
  test/test_delete.py
  test/test_delete_user.py
  test/test_display.py
  test/test_edit.py
  test/test_estimate.py
  test/test_graph.py
  test/test_helper.py
  test/test_history.py
  test/test_pdf.py
  test/test_send_mail.py
Labels: bug

#27 24 add ocr feature for reading bill invoice image and extracting expenditure data
  README.md
  code/code.py
  code/ocr.py
  histo.png
  invoice.jpg
Labels: enhancement, user experience

#31 Release v2.0
  docs/add.png
  docs/add_user.md
  docs/addd.png
  docs/adduser.png
  docs/csv.png
  docs/csvfile.md
  docs/csvss.png
  docs/delete_user.md
  docs/deleteuser.png
  docs/ocr.md
  docs/ocr1.png
  docs/ocr2.png
  docs/pdf.md
  docs/pdf.png
  docs/pdfoptiona.png
  docs/pdfoptionb.png
  docs/pdfoptions.png
  docs/send_mail.md
  docs/sendmail.png
  docs/sendmailss.jpeg
Labels: documentation, enhancement

#33 Closing 32 add demo gif for ocr invoice feature
  OCR - DollarBot.gif
  README.md
Labels: documentation
